spring:
  profiles:
    active: real,oauth,real-db

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      maxFileSize : 10MB
      maxRequestSize : 10MB

logging:
  level:
    root: info
    org.hibernate.SQL: info
  file:
    path: logs

