spring:
  profiles:
    include: oauth,init

  session:
    store-type : jdbc
    jdbc.initialize-schema: always

  datasource:
    url:  jdbc:h2:tcp://localhost/~/db/inha
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug