spring:
  profiles:
    active: real,oauth,real-db

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

logging:
  level:
    root: info
    org.hibernate.SQL: info
  file:
    path: logs

