spring:
  profiles:
    active: real,oauth,real-db

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug

